# Generated by Django 6.0.6 on 2026-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Rasm URL (imgbb.com dan)'),
        ),
    ]
